namespace ElMirador.Presentacion.Ventas
{
    partial class FrmEditorCliente
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmEditorCliente));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.PnlPrincipal = new System.Windows.Forms.Panel();
            this.FlwPnlBotones = new System.Windows.Forms.FlowLayoutPanel();
            this.BtnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnLimpiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.TbPnlUbicacion = new System.Windows.Forms.TableLayoutPanel();
            this.LblDepartamento = new System.Windows.Forms.Label();
            this.LblMunicipio = new System.Windows.Forms.Label();
            this.CmbDepartamentos = new System.Windows.Forms.ComboBox();
            this.CmbMunicipios = new System.Windows.Forms.ComboBox();
            this.LblUbicacion = new System.Windows.Forms.Label();
            this.TbPnlOtrosDatos = new System.Windows.Forms.TableLayoutPanel();
            this.TxtTelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtDireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LblOtrosDatos = new System.Windows.Forms.Label();
            this.TbPnlNombresCliente = new System.Windows.Forms.TableLayoutPanel();
            this.TxtPrimerNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtSegundoNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtPrimerApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TxtSegundoApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LblNombresCliente = new System.Windows.Forms.Label();
            this.PnlPrincipal.SuspendLayout();
            this.FlwPnlBotones.SuspendLayout();
            this.TbPnlUbicacion.SuspendLayout();
            this.TbPnlOtrosDatos.SuspendLayout();
            this.TbPnlNombresCliente.SuspendLayout();
            this.SuspendLayout();
            // 
            // PnlPrincipal
            // 
            this.PnlPrincipal.AutoScroll = true;
            this.PnlPrincipal.Controls.Add(this.FlwPnlBotones);
            this.PnlPrincipal.Controls.Add(this.label1);
            this.PnlPrincipal.Controls.Add(this.TbPnlUbicacion);
            this.PnlPrincipal.Controls.Add(this.LblUbicacion);
            this.PnlPrincipal.Controls.Add(this.TbPnlOtrosDatos);
            this.PnlPrincipal.Controls.Add(this.LblOtrosDatos);
            this.PnlPrincipal.Controls.Add(this.TbPnlNombresCliente);
            this.PnlPrincipal.Controls.Add(this.LblNombresCliente);
            this.PnlPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PnlPrincipal.Location = new System.Drawing.Point(0, 0);
            this.PnlPrincipal.Name = "PnlPrincipal";
            this.PnlPrincipal.Size = new System.Drawing.Size(800, 450);
            this.PnlPrincipal.TabIndex = 0;
            // 
            // FlwPnlBotones
            // 
            this.FlwPnlBotones.Controls.Add(this.BtnGuardar);
            this.FlwPnlBotones.Controls.Add(this.BtnLimpiar);
            this.FlwPnlBotones.Controls.Add(this.BtnCancelar);
            this.FlwPnlBotones.Dock = System.Windows.Forms.DockStyle.Top;
            this.FlwPnlBotones.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.FlwPnlBotones.Location = new System.Drawing.Point(0, 412);
            this.FlwPnlBotones.Name = "FlwPnlBotones";
            this.FlwPnlBotones.Size = new System.Drawing.Size(783, 54);
            this.FlwPnlBotones.TabIndex = 7;
            // 
            // BtnGuardar
            // 
            this.BtnGuardar.AllowAnimations = true;
            this.BtnGuardar.AllowMouseEffects = true;
            this.BtnGuardar.AllowToggling = false;
            this.BtnGuardar.AnimationSpeed = 200;
            this.BtnGuardar.AutoGenerateColors = false;
            this.BtnGuardar.AutoRoundBorders = false;
            this.BtnGuardar.AutoSizeLeftIcon = true;
            this.BtnGuardar.AutoSizeRightIcon = true;
            this.BtnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.BtnGuardar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnGuardar.BackgroundImage")));
            this.BtnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.ButtonText = "Guardar";
            this.BtnGuardar.ButtonTextMarginLeft = 0;
            this.BtnGuardar.ColorContrastOnClick = 45;
            this.BtnGuardar.ColorContrastOnHover = 45;
            this.BtnGuardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnGuardar.CustomizableEdges = borderEdges1;
            this.BtnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnGuardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnGuardar.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnGuardar.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnGuardar.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.IconLeft = null;
            this.BtnGuardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnGuardar.IconMarginLeft = 11;
            this.BtnGuardar.IconPadding = 10;
            this.BtnGuardar.IconRight = null;
            this.BtnGuardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnGuardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnGuardar.IconSize = 25;
            this.BtnGuardar.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnGuardar.IdleBorderRadius = 0;
            this.BtnGuardar.IdleBorderThickness = 0;
            this.BtnGuardar.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnGuardar.IdleIconLeftImage = null;
            this.BtnGuardar.IdleIconRightImage = null;
            this.BtnGuardar.IndicateFocus = false;
            this.BtnGuardar.Location = new System.Drawing.Point(630, 3);
            this.BtnGuardar.Name = "BtnGuardar";
            this.BtnGuardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnGuardar.OnDisabledState.BorderRadius = 10;
            this.BtnGuardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnDisabledState.BorderThickness = 1;
            this.BtnGuardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnGuardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnGuardar.OnDisabledState.IconLeftImage = null;
            this.BtnGuardar.OnDisabledState.IconRightImage = null;
            this.BtnGuardar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnGuardar.onHoverState.BorderRadius = 10;
            this.BtnGuardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.onHoverState.BorderThickness = 1;
            this.BtnGuardar.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnGuardar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnGuardar.onHoverState.IconLeftImage = null;
            this.BtnGuardar.onHoverState.IconRightImage = null;
            this.BtnGuardar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnGuardar.OnIdleState.BorderRadius = 10;
            this.BtnGuardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnIdleState.BorderThickness = 1;
            this.BtnGuardar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnGuardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnIdleState.IconLeftImage = null;
            this.BtnGuardar.OnIdleState.IconRightImage = null;
            this.BtnGuardar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnGuardar.OnPressedState.BorderRadius = 10;
            this.BtnGuardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnGuardar.OnPressedState.BorderThickness = 1;
            this.BtnGuardar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnGuardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnGuardar.OnPressedState.IconLeftImage = null;
            this.BtnGuardar.OnPressedState.IconRightImage = null;
            this.BtnGuardar.Size = new System.Drawing.Size(150, 39);
            this.BtnGuardar.TabIndex = 0;
            this.BtnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnGuardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnGuardar.TextMarginLeft = 0;
            this.BtnGuardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnGuardar.UseDefaultRadiusAndThickness = true;
            this.BtnGuardar.Click += new System.EventHandler(this.BtnGuardar_Click);
            // 
            // BtnLimpiar
            // 
            this.BtnLimpiar.AllowAnimations = true;
            this.BtnLimpiar.AllowMouseEffects = true;
            this.BtnLimpiar.AllowToggling = false;
            this.BtnLimpiar.AnimationSpeed = 200;
            this.BtnLimpiar.AutoGenerateColors = false;
            this.BtnLimpiar.AutoRoundBorders = false;
            this.BtnLimpiar.AutoSizeLeftIcon = true;
            this.BtnLimpiar.AutoSizeRightIcon = true;
            this.BtnLimpiar.BackColor = System.Drawing.Color.Transparent;
            this.BtnLimpiar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnLimpiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnLimpiar.BackgroundImage")));
            this.BtnLimpiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLimpiar.ButtonText = "Limpiar";
            this.BtnLimpiar.ButtonTextMarginLeft = 0;
            this.BtnLimpiar.ColorContrastOnClick = 45;
            this.BtnLimpiar.ColorContrastOnHover = 45;
            this.BtnLimpiar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnLimpiar.CustomizableEdges = borderEdges2;
            this.BtnLimpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnLimpiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLimpiar.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnLimpiar.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnLimpiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnLimpiar.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnLimpiar.ForeColor = System.Drawing.Color.Black;
            this.BtnLimpiar.IconLeft = null;
            this.BtnLimpiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnLimpiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLimpiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnLimpiar.IconMarginLeft = 11;
            this.BtnLimpiar.IconPadding = 10;
            this.BtnLimpiar.IconRight = null;
            this.BtnLimpiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnLimpiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLimpiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnLimpiar.IconSize = 25;
            this.BtnLimpiar.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnLimpiar.IdleBorderRadius = 0;
            this.BtnLimpiar.IdleBorderThickness = 0;
            this.BtnLimpiar.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnLimpiar.IdleIconLeftImage = null;
            this.BtnLimpiar.IdleIconRightImage = null;
            this.BtnLimpiar.IndicateFocus = false;
            this.BtnLimpiar.Location = new System.Drawing.Point(474, 3);
            this.BtnLimpiar.Name = "BtnLimpiar";
            this.BtnLimpiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLimpiar.OnDisabledState.BorderRadius = 10;
            this.BtnLimpiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLimpiar.OnDisabledState.BorderThickness = 1;
            this.BtnLimpiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnLimpiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnLimpiar.OnDisabledState.IconLeftImage = null;
            this.BtnLimpiar.OnDisabledState.IconRightImage = null;
            this.BtnLimpiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnLimpiar.onHoverState.BorderRadius = 10;
            this.BtnLimpiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLimpiar.onHoverState.BorderThickness = 1;
            this.BtnLimpiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnLimpiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnLimpiar.onHoverState.IconLeftImage = null;
            this.BtnLimpiar.onHoverState.IconRightImage = null;
            this.BtnLimpiar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnLimpiar.OnIdleState.BorderRadius = 10;
            this.BtnLimpiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLimpiar.OnIdleState.BorderThickness = 1;
            this.BtnLimpiar.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BtnLimpiar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.BtnLimpiar.OnIdleState.IconLeftImage = null;
            this.BtnLimpiar.OnIdleState.IconRightImage = null;
            this.BtnLimpiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnLimpiar.OnPressedState.BorderRadius = 10;
            this.BtnLimpiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLimpiar.OnPressedState.BorderThickness = 1;
            this.BtnLimpiar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnLimpiar.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnLimpiar.OnPressedState.IconLeftImage = null;
            this.BtnLimpiar.OnPressedState.IconRightImage = null;
            this.BtnLimpiar.Size = new System.Drawing.Size(150, 39);
            this.BtnLimpiar.TabIndex = 1;
            this.BtnLimpiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnLimpiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnLimpiar.TextMarginLeft = 0;
            this.BtnLimpiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnLimpiar.UseDefaultRadiusAndThickness = true;
            this.BtnLimpiar.Click += new System.EventHandler(this.BtnLimpiar_Click);
            // 
            // BtnCancelar
            // 
            this.BtnCancelar.AllowAnimations = true;
            this.BtnCancelar.AllowMouseEffects = true;
            this.BtnCancelar.AllowToggling = false;
            this.BtnCancelar.AnimationSpeed = 200;
            this.BtnCancelar.AutoGenerateColors = false;
            this.BtnCancelar.AutoRoundBorders = false;
            this.BtnCancelar.AutoSizeLeftIcon = true;
            this.BtnCancelar.AutoSizeRightIcon = true;
            this.BtnCancelar.BackColor = System.Drawing.Color.Transparent;
            this.BtnCancelar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCancelar.BackgroundImage")));
            this.BtnCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.ButtonText = "Cancelar";
            this.BtnCancelar.ButtonTextMarginLeft = 0;
            this.BtnCancelar.ColorContrastOnClick = 45;
            this.BtnCancelar.ColorContrastOnHover = 45;
            this.BtnCancelar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnCancelar.CustomizableEdges = borderEdges3;
            this.BtnCancelar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCancelar.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCancelar.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCancelar.ForeColor = System.Drawing.Color.Black;
            this.BtnCancelar.IconLeft = null;
            this.BtnCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCancelar.IconMarginLeft = 11;
            this.BtnCancelar.IconPadding = 10;
            this.BtnCancelar.IconRight = null;
            this.BtnCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCancelar.IconSize = 25;
            this.BtnCancelar.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCancelar.IdleBorderRadius = 0;
            this.BtnCancelar.IdleBorderThickness = 0;
            this.BtnCancelar.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCancelar.IdleIconLeftImage = null;
            this.BtnCancelar.IdleIconRightImage = null;
            this.BtnCancelar.IndicateFocus = false;
            this.BtnCancelar.Location = new System.Drawing.Point(318, 3);
            this.BtnCancelar.Name = "BtnCancelar";
            this.BtnCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCancelar.OnDisabledState.BorderRadius = 10;
            this.BtnCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnDisabledState.BorderThickness = 1;
            this.BtnCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCancelar.OnDisabledState.IconLeftImage = null;
            this.BtnCancelar.OnDisabledState.IconRightImage = null;
            this.BtnCancelar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(191)))), ((int)(((byte)(63)))));
            this.BtnCancelar.onHoverState.BorderRadius = 10;
            this.BtnCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.onHoverState.BorderThickness = 1;
            this.BtnCancelar.onHoverState.FillColor = System.Drawing.Color.White;
            this.BtnCancelar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnCancelar.onHoverState.IconLeftImage = null;
            this.BtnCancelar.onHoverState.IconRightImage = null;
            this.BtnCancelar.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.BtnCancelar.OnIdleState.BorderRadius = 10;
            this.BtnCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnIdleState.BorderThickness = 1;
            this.BtnCancelar.OnIdleState.FillColor = System.Drawing.Color.White;
            this.BtnCancelar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.BtnCancelar.OnIdleState.IconLeftImage = null;
            this.BtnCancelar.OnIdleState.IconRightImage = null;
            this.BtnCancelar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.BtnCancelar.OnPressedState.BorderRadius = 10;
            this.BtnCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCancelar.OnPressedState.BorderThickness = 1;
            this.BtnCancelar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.BtnCancelar.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnCancelar.OnPressedState.IconLeftImage = null;
            this.BtnCancelar.OnPressedState.IconRightImage = null;
            this.BtnCancelar.Size = new System.Drawing.Size(150, 39);
            this.BtnCancelar.TabIndex = 2;
            this.BtnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCancelar.TextMarginLeft = 0;
            this.BtnCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCancelar.UseDefaultRadiusAndThickness = true;
            this.BtnCancelar.Click += new System.EventHandler(this.BtnCancelar_Click);
            // 
            // label1
            // 
            this.label1.Dock = System.Windows.Forms.DockStyle.Top;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(0, 369);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(783, 43);
            this.label1.TabIndex = 6;
            this.label1.Text = "¡Has finalizado!";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // TbPnlUbicacion
            // 
            this.TbPnlUbicacion.ColumnCount = 4;
            this.TbPnlUbicacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.TbPnlUbicacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 47F));
            this.TbPnlUbicacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 47F));
            this.TbPnlUbicacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.TbPnlUbicacion.Controls.Add(this.LblDepartamento, 1, 0);
            this.TbPnlUbicacion.Controls.Add(this.LblMunicipio, 2, 0);
            this.TbPnlUbicacion.Controls.Add(this.CmbDepartamentos, 1, 1);
            this.TbPnlUbicacion.Controls.Add(this.CmbMunicipios, 2, 1);
            this.TbPnlUbicacion.Dock = System.Windows.Forms.DockStyle.Top;
            this.TbPnlUbicacion.Location = new System.Drawing.Point(0, 287);
            this.TbPnlUbicacion.Name = "TbPnlUbicacion";
            this.TbPnlUbicacion.RowCount = 2;
            this.TbPnlUbicacion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 57.31707F));
            this.TbPnlUbicacion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 42.68293F));
            this.TbPnlUbicacion.Size = new System.Drawing.Size(783, 82);
            this.TbPnlUbicacion.TabIndex = 5;
            // 
            // LblDepartamento
            // 
            this.LblDepartamento.Dock = System.Windows.Forms.DockStyle.Fill;
            this.LblDepartamento.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblDepartamento.Location = new System.Drawing.Point(26, 0);
            this.LblDepartamento.Name = "LblDepartamento";
            this.LblDepartamento.Size = new System.Drawing.Size(362, 46);
            this.LblDepartamento.TabIndex = 0;
            this.LblDepartamento.Text = "Departamento";
            this.LblDepartamento.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // LblMunicipio
            // 
            this.LblMunicipio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.LblMunicipio.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblMunicipio.Location = new System.Drawing.Point(394, 0);
            this.LblMunicipio.Name = "LblMunicipio";
            this.LblMunicipio.Size = new System.Drawing.Size(362, 46);
            this.LblMunicipio.TabIndex = 1;
            this.LblMunicipio.Text = "Municipio";
            this.LblMunicipio.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // CmbDepartamentos
            // 
            this.CmbDepartamentos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CmbDepartamentos.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CmbDepartamentos.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CmbDepartamentos.FormattingEnabled = true;
            this.CmbDepartamentos.Location = new System.Drawing.Point(26, 49);
            this.CmbDepartamentos.Name = "CmbDepartamentos";
            this.CmbDepartamentos.Size = new System.Drawing.Size(362, 24);
            this.CmbDepartamentos.TabIndex = 2;
            this.CmbDepartamentos.SelectedIndexChanged += new System.EventHandler(this.CmbDepartamentos_SelectedIndexChanged);
            // 
            // CmbMunicipios
            // 
            this.CmbMunicipios.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CmbMunicipios.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.CmbMunicipios.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CmbMunicipios.FormattingEnabled = true;
            this.CmbMunicipios.Location = new System.Drawing.Point(394, 49);
            this.CmbMunicipios.Name = "CmbMunicipios";
            this.CmbMunicipios.Size = new System.Drawing.Size(362, 24);
            this.CmbMunicipios.TabIndex = 3;
            // 
            // LblUbicacion
            // 
            this.LblUbicacion.Dock = System.Windows.Forms.DockStyle.Top;
            this.LblUbicacion.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblUbicacion.Location = new System.Drawing.Point(0, 244);
            this.LblUbicacion.Name = "LblUbicacion";
            this.LblUbicacion.Size = new System.Drawing.Size(783, 43);
            this.LblUbicacion.TabIndex = 4;
            this.LblUbicacion.Text = "¿Cómo lo ubicamos?";
            this.LblUbicacion.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // TbPnlOtrosDatos
            // 
            this.TbPnlOtrosDatos.ColumnCount = 4;
            this.TbPnlOtrosDatos.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.TbPnlOtrosDatos.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 47F));
            this.TbPnlOtrosDatos.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 47F));
            this.TbPnlOtrosDatos.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.TbPnlOtrosDatos.Controls.Add(this.TxtTelefono, 1, 0);
            this.TbPnlOtrosDatos.Controls.Add(this.TxtDireccion, 2, 0);
            this.TbPnlOtrosDatos.Dock = System.Windows.Forms.DockStyle.Top;
            this.TbPnlOtrosDatos.Location = new System.Drawing.Point(0, 186);
            this.TbPnlOtrosDatos.Name = "TbPnlOtrosDatos";
            this.TbPnlOtrosDatos.RowCount = 1;
            this.TbPnlOtrosDatos.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TbPnlOtrosDatos.Size = new System.Drawing.Size(783, 58);
            this.TbPnlOtrosDatos.TabIndex = 3;
            // 
            // TxtTelefono
            // 
            this.TxtTelefono.AcceptsReturn = false;
            this.TxtTelefono.AcceptsTab = false;
            this.TxtTelefono.AnimationSpeed = 200;
            this.TxtTelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtTelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtTelefono.AutoSizeHeight = true;
            this.TxtTelefono.BackColor = System.Drawing.Color.Transparent;
            this.TxtTelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtTelefono.BackgroundImage")));
            this.TxtTelefono.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtTelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtTelefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtTelefono.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtTelefono.BorderRadius = 10;
            this.TxtTelefono.BorderThickness = 1;
            this.TxtTelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtTelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtTelefono.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TxtTelefono.DefaultText = "";
            this.TxtTelefono.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TxtTelefono.FillColor = System.Drawing.Color.White;
            this.TxtTelefono.ForeColor = System.Drawing.Color.Black;
            this.TxtTelefono.HideSelection = true;
            this.TxtTelefono.IconLeft = null;
            this.TxtTelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtTelefono.IconPadding = 10;
            this.TxtTelefono.IconRight = null;
            this.TxtTelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtTelefono.Lines = new string[0];
            this.TxtTelefono.Location = new System.Drawing.Point(26, 3);
            this.TxtTelefono.MaxLength = 32767;
            this.TxtTelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtTelefono.Modified = false;
            this.TxtTelefono.Multiline = false;
            this.TxtTelefono.Name = "TxtTelefono";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties1.FillColor = System.Drawing.Color.White;
            stateProperties1.ForeColor = System.Drawing.Color.Black;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtTelefono.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtTelefono.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties3.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties3.ForeColor = System.Drawing.Color.Black;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtTelefono.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtTelefono.OnIdleState = stateProperties4;
            this.TxtTelefono.Padding = new System.Windows.Forms.Padding(3);
            this.TxtTelefono.PasswordChar = '\0';
            this.TxtTelefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtTelefono.PlaceholderText = "Teléfono";
            this.TxtTelefono.ReadOnly = false;
            this.TxtTelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtTelefono.SelectedText = "";
            this.TxtTelefono.SelectionLength = 0;
            this.TxtTelefono.SelectionStart = 0;
            this.TxtTelefono.ShortcutsEnabled = true;
            this.TxtTelefono.Size = new System.Drawing.Size(362, 52);
            this.TxtTelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtTelefono.TabIndex = 0;
            this.TxtTelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtTelefono.TextMarginBottom = 0;
            this.TxtTelefono.TextMarginLeft = 3;
            this.TxtTelefono.TextMarginTop = 1;
            this.TxtTelefono.TextPlaceholder = "Teléfono";
            this.TxtTelefono.UseSystemPasswordChar = false;
            this.TxtTelefono.WordWrap = true;
            // 
            // TxtDireccion
            // 
            this.TxtDireccion.AcceptsReturn = false;
            this.TxtDireccion.AcceptsTab = false;
            this.TxtDireccion.AnimationSpeed = 200;
            this.TxtDireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtDireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtDireccion.AutoSizeHeight = true;
            this.TxtDireccion.BackColor = System.Drawing.Color.Transparent;
            this.TxtDireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtDireccion.BackgroundImage")));
            this.TxtDireccion.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtDireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtDireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtDireccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtDireccion.BorderRadius = 10;
            this.TxtDireccion.BorderThickness = 1;
            this.TxtDireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtDireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDireccion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TxtDireccion.DefaultText = "";
            this.TxtDireccion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TxtDireccion.FillColor = System.Drawing.Color.White;
            this.TxtDireccion.ForeColor = System.Drawing.Color.Black;
            this.TxtDireccion.HideSelection = true;
            this.TxtDireccion.IconLeft = null;
            this.TxtDireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDireccion.IconPadding = 10;
            this.TxtDireccion.IconRight = null;
            this.TxtDireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtDireccion.Lines = new string[0];
            this.TxtDireccion.Location = new System.Drawing.Point(394, 3);
            this.TxtDireccion.MaxLength = 32767;
            this.TxtDireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtDireccion.Modified = false;
            this.TxtDireccion.Multiline = true;
            this.TxtDireccion.Name = "TxtDireccion";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties5.FillColor = System.Drawing.Color.White;
            stateProperties5.ForeColor = System.Drawing.Color.Black;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtDireccion.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtDireccion.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties7.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties7.ForeColor = System.Drawing.Color.Black;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtDireccion.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtDireccion.OnIdleState = stateProperties8;
            this.TxtDireccion.Padding = new System.Windows.Forms.Padding(3);
            this.TxtDireccion.PasswordChar = '\0';
            this.TxtDireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtDireccion.PlaceholderText = "Dirección";
            this.TxtDireccion.ReadOnly = false;
            this.TxtDireccion.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.TxtDireccion.SelectedText = "";
            this.TxtDireccion.SelectionLength = 0;
            this.TxtDireccion.SelectionStart = 0;
            this.TxtDireccion.ShortcutsEnabled = true;
            this.TxtDireccion.Size = new System.Drawing.Size(362, 52);
            this.TxtDireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtDireccion.TabIndex = 1;
            this.TxtDireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtDireccion.TextMarginBottom = 0;
            this.TxtDireccion.TextMarginLeft = 3;
            this.TxtDireccion.TextMarginTop = 1;
            this.TxtDireccion.TextPlaceholder = "Dirección";
            this.TxtDireccion.UseSystemPasswordChar = false;
            this.TxtDireccion.WordWrap = true;
            // 
            // LblOtrosDatos
            // 
            this.LblOtrosDatos.Dock = System.Windows.Forms.DockStyle.Top;
            this.LblOtrosDatos.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblOtrosDatos.Location = new System.Drawing.Point(0, 143);
            this.LblOtrosDatos.Name = "LblOtrosDatos";
            this.LblOtrosDatos.Size = new System.Drawing.Size(783, 43);
            this.LblOtrosDatos.TabIndex = 2;
            this.LblOtrosDatos.Text = "Otros datos sobre el cliente.";
            this.LblOtrosDatos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // TbPnlNombresCliente
            // 
            this.TbPnlNombresCliente.ColumnCount = 4;
            this.TbPnlNombresCliente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.TbPnlNombresCliente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 47F));
            this.TbPnlNombresCliente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 47F));
            this.TbPnlNombresCliente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.TbPnlNombresCliente.Controls.Add(this.TxtPrimerNombre, 1, 0);
            this.TbPnlNombresCliente.Controls.Add(this.TxtSegundoNombre, 2, 0);
            this.TbPnlNombresCliente.Controls.Add(this.TxtPrimerApellido, 1, 1);
            this.TbPnlNombresCliente.Controls.Add(this.TxtSegundoApellido, 2, 1);
            this.TbPnlNombresCliente.Dock = System.Windows.Forms.DockStyle.Top;
            this.TbPnlNombresCliente.Location = new System.Drawing.Point(0, 43);
            this.TbPnlNombresCliente.Name = "TbPnlNombresCliente";
            this.TbPnlNombresCliente.RowCount = 2;
            this.TbPnlNombresCliente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TbPnlNombresCliente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TbPnlNombresCliente.Size = new System.Drawing.Size(783, 100);
            this.TbPnlNombresCliente.TabIndex = 1;
            // 
            // TxtPrimerNombre
            // 
            this.TxtPrimerNombre.AcceptsReturn = false;
            this.TxtPrimerNombre.AcceptsTab = false;
            this.TxtPrimerNombre.AnimationSpeed = 200;
            this.TxtPrimerNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtPrimerNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtPrimerNombre.AutoSizeHeight = true;
            this.TxtPrimerNombre.BackColor = System.Drawing.Color.Transparent;
            this.TxtPrimerNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtPrimerNombre.BackgroundImage")));
            this.TxtPrimerNombre.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtPrimerNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtPrimerNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtPrimerNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtPrimerNombre.BorderRadius = 10;
            this.TxtPrimerNombre.BorderThickness = 1;
            this.TxtPrimerNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtPrimerNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrimerNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TxtPrimerNombre.DefaultText = "";
            this.TxtPrimerNombre.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TxtPrimerNombre.FillColor = System.Drawing.Color.White;
            this.TxtPrimerNombre.ForeColor = System.Drawing.Color.Black;
            this.TxtPrimerNombre.HideSelection = true;
            this.TxtPrimerNombre.IconLeft = null;
            this.TxtPrimerNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrimerNombre.IconPadding = 10;
            this.TxtPrimerNombre.IconRight = null;
            this.TxtPrimerNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrimerNombre.Lines = new string[0];
            this.TxtPrimerNombre.Location = new System.Drawing.Point(26, 3);
            this.TxtPrimerNombre.MaxLength = 32767;
            this.TxtPrimerNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtPrimerNombre.Modified = false;
            this.TxtPrimerNombre.Multiline = false;
            this.TxtPrimerNombre.Name = "TxtPrimerNombre";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties9.FillColor = System.Drawing.Color.White;
            stateProperties9.ForeColor = System.Drawing.Color.Black;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtPrimerNombre.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtPrimerNombre.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties11.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties11.ForeColor = System.Drawing.Color.Black;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtPrimerNombre.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPrimerNombre.OnIdleState = stateProperties12;
            this.TxtPrimerNombre.Padding = new System.Windows.Forms.Padding(3);
            this.TxtPrimerNombre.PasswordChar = '\0';
            this.TxtPrimerNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPrimerNombre.PlaceholderText = "Primer Nombre";
            this.TxtPrimerNombre.ReadOnly = false;
            this.TxtPrimerNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtPrimerNombre.SelectedText = "";
            this.TxtPrimerNombre.SelectionLength = 0;
            this.TxtPrimerNombre.SelectionStart = 0;
            this.TxtPrimerNombre.ShortcutsEnabled = true;
            this.TxtPrimerNombre.Size = new System.Drawing.Size(362, 44);
            this.TxtPrimerNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtPrimerNombre.TabIndex = 0;
            this.TxtPrimerNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtPrimerNombre.TextMarginBottom = 0;
            this.TxtPrimerNombre.TextMarginLeft = 3;
            this.TxtPrimerNombre.TextMarginTop = 1;
            this.TxtPrimerNombre.TextPlaceholder = "Primer Nombre";
            this.TxtPrimerNombre.UseSystemPasswordChar = false;
            this.TxtPrimerNombre.WordWrap = true;
            // 
            // TxtSegundoNombre
            // 
            this.TxtSegundoNombre.AcceptsReturn = false;
            this.TxtSegundoNombre.AcceptsTab = false;
            this.TxtSegundoNombre.AnimationSpeed = 200;
            this.TxtSegundoNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtSegundoNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtSegundoNombre.AutoSizeHeight = true;
            this.TxtSegundoNombre.BackColor = System.Drawing.Color.Transparent;
            this.TxtSegundoNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtSegundoNombre.BackgroundImage")));
            this.TxtSegundoNombre.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtSegundoNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtSegundoNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtSegundoNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtSegundoNombre.BorderRadius = 10;
            this.TxtSegundoNombre.BorderThickness = 1;
            this.TxtSegundoNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtSegundoNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtSegundoNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TxtSegundoNombre.DefaultText = "";
            this.TxtSegundoNombre.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TxtSegundoNombre.FillColor = System.Drawing.Color.White;
            this.TxtSegundoNombre.ForeColor = System.Drawing.Color.Black;
            this.TxtSegundoNombre.HideSelection = true;
            this.TxtSegundoNombre.IconLeft = null;
            this.TxtSegundoNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtSegundoNombre.IconPadding = 10;
            this.TxtSegundoNombre.IconRight = null;
            this.TxtSegundoNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtSegundoNombre.Lines = new string[0];
            this.TxtSegundoNombre.Location = new System.Drawing.Point(394, 3);
            this.TxtSegundoNombre.MaxLength = 32767;
            this.TxtSegundoNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtSegundoNombre.Modified = false;
            this.TxtSegundoNombre.Multiline = false;
            this.TxtSegundoNombre.Name = "TxtSegundoNombre";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties13.FillColor = System.Drawing.Color.White;
            stateProperties13.ForeColor = System.Drawing.Color.Black;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtSegundoNombre.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtSegundoNombre.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties15.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties15.ForeColor = System.Drawing.Color.Black;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtSegundoNombre.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtSegundoNombre.OnIdleState = stateProperties16;
            this.TxtSegundoNombre.Padding = new System.Windows.Forms.Padding(3);
            this.TxtSegundoNombre.PasswordChar = '\0';
            this.TxtSegundoNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtSegundoNombre.PlaceholderText = "Segundo Nombre";
            this.TxtSegundoNombre.ReadOnly = false;
            this.TxtSegundoNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtSegundoNombre.SelectedText = "";
            this.TxtSegundoNombre.SelectionLength = 0;
            this.TxtSegundoNombre.SelectionStart = 0;
            this.TxtSegundoNombre.ShortcutsEnabled = true;
            this.TxtSegundoNombre.Size = new System.Drawing.Size(362, 44);
            this.TxtSegundoNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtSegundoNombre.TabIndex = 1;
            this.TxtSegundoNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtSegundoNombre.TextMarginBottom = 0;
            this.TxtSegundoNombre.TextMarginLeft = 3;
            this.TxtSegundoNombre.TextMarginTop = 1;
            this.TxtSegundoNombre.TextPlaceholder = "Segundo Nombre";
            this.TxtSegundoNombre.UseSystemPasswordChar = false;
            this.TxtSegundoNombre.WordWrap = true;
            // 
            // TxtPrimerApellido
            // 
            this.TxtPrimerApellido.AcceptsReturn = false;
            this.TxtPrimerApellido.AcceptsTab = false;
            this.TxtPrimerApellido.AnimationSpeed = 200;
            this.TxtPrimerApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtPrimerApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtPrimerApellido.AutoSizeHeight = true;
            this.TxtPrimerApellido.BackColor = System.Drawing.Color.Transparent;
            this.TxtPrimerApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtPrimerApellido.BackgroundImage")));
            this.TxtPrimerApellido.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtPrimerApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtPrimerApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtPrimerApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtPrimerApellido.BorderRadius = 10;
            this.TxtPrimerApellido.BorderThickness = 1;
            this.TxtPrimerApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtPrimerApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrimerApellido.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TxtPrimerApellido.DefaultText = "";
            this.TxtPrimerApellido.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TxtPrimerApellido.FillColor = System.Drawing.Color.White;
            this.TxtPrimerApellido.ForeColor = System.Drawing.Color.Black;
            this.TxtPrimerApellido.HideSelection = true;
            this.TxtPrimerApellido.IconLeft = null;
            this.TxtPrimerApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrimerApellido.IconPadding = 10;
            this.TxtPrimerApellido.IconRight = null;
            this.TxtPrimerApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtPrimerApellido.Lines = new string[0];
            this.TxtPrimerApellido.Location = new System.Drawing.Point(26, 53);
            this.TxtPrimerApellido.MaxLength = 32767;
            this.TxtPrimerApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtPrimerApellido.Modified = false;
            this.TxtPrimerApellido.Multiline = false;
            this.TxtPrimerApellido.Name = "TxtPrimerApellido";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties17.FillColor = System.Drawing.Color.White;
            stateProperties17.ForeColor = System.Drawing.Color.Black;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtPrimerApellido.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtPrimerApellido.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties19.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties19.ForeColor = System.Drawing.Color.Black;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtPrimerApellido.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPrimerApellido.OnIdleState = stateProperties20;
            this.TxtPrimerApellido.Padding = new System.Windows.Forms.Padding(3);
            this.TxtPrimerApellido.PasswordChar = '\0';
            this.TxtPrimerApellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtPrimerApellido.PlaceholderText = "Primer Apellido";
            this.TxtPrimerApellido.ReadOnly = false;
            this.TxtPrimerApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtPrimerApellido.SelectedText = "";
            this.TxtPrimerApellido.SelectionLength = 0;
            this.TxtPrimerApellido.SelectionStart = 0;
            this.TxtPrimerApellido.ShortcutsEnabled = true;
            this.TxtPrimerApellido.Size = new System.Drawing.Size(362, 44);
            this.TxtPrimerApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtPrimerApellido.TabIndex = 2;
            this.TxtPrimerApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtPrimerApellido.TextMarginBottom = 0;
            this.TxtPrimerApellido.TextMarginLeft = 3;
            this.TxtPrimerApellido.TextMarginTop = 1;
            this.TxtPrimerApellido.TextPlaceholder = "Primer Apellido";
            this.TxtPrimerApellido.UseSystemPasswordChar = false;
            this.TxtPrimerApellido.WordWrap = true;
            // 
            // TxtSegundoApellido
            // 
            this.TxtSegundoApellido.AcceptsReturn = false;
            this.TxtSegundoApellido.AcceptsTab = false;
            this.TxtSegundoApellido.AnimationSpeed = 200;
            this.TxtSegundoApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TxtSegundoApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TxtSegundoApellido.AutoSizeHeight = true;
            this.TxtSegundoApellido.BackColor = System.Drawing.Color.Transparent;
            this.TxtSegundoApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TxtSegundoApellido.BackgroundImage")));
            this.TxtSegundoApellido.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtSegundoApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TxtSegundoApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            this.TxtSegundoApellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.TxtSegundoApellido.BorderRadius = 10;
            this.TxtSegundoApellido.BorderThickness = 1;
            this.TxtSegundoApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TxtSegundoApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtSegundoApellido.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TxtSegundoApellido.DefaultText = "";
            this.TxtSegundoApellido.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TxtSegundoApellido.FillColor = System.Drawing.Color.White;
            this.TxtSegundoApellido.ForeColor = System.Drawing.Color.Black;
            this.TxtSegundoApellido.HideSelection = true;
            this.TxtSegundoApellido.IconLeft = null;
            this.TxtSegundoApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtSegundoApellido.IconPadding = 10;
            this.TxtSegundoApellido.IconRight = null;
            this.TxtSegundoApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TxtSegundoApellido.Lines = new string[0];
            this.TxtSegundoApellido.Location = new System.Drawing.Point(394, 53);
            this.TxtSegundoApellido.MaxLength = 32767;
            this.TxtSegundoApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.TxtSegundoApellido.Modified = false;
            this.TxtSegundoApellido.Multiline = false;
            this.TxtSegundoApellido.Name = "TxtSegundoApellido";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties21.FillColor = System.Drawing.Color.White;
            stateProperties21.ForeColor = System.Drawing.Color.Black;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtSegundoApellido.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TxtSegundoApellido.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties23.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(199)))), ((int)(((byte)(242)))));
            stateProperties23.ForeColor = System.Drawing.Color.Black;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Black;
            this.TxtSegundoApellido.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtSegundoApellido.OnIdleState = stateProperties24;
            this.TxtSegundoApellido.Padding = new System.Windows.Forms.Padding(3);
            this.TxtSegundoApellido.PasswordChar = '\0';
            this.TxtSegundoApellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TxtSegundoApellido.PlaceholderText = "Segundo Apellido";
            this.TxtSegundoApellido.ReadOnly = false;
            this.TxtSegundoApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TxtSegundoApellido.SelectedText = "";
            this.TxtSegundoApellido.SelectionLength = 0;
            this.TxtSegundoApellido.SelectionStart = 0;
            this.TxtSegundoApellido.ShortcutsEnabled = true;
            this.TxtSegundoApellido.Size = new System.Drawing.Size(362, 44);
            this.TxtSegundoApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.TxtSegundoApellido.TabIndex = 3;
            this.TxtSegundoApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TxtSegundoApellido.TextMarginBottom = 0;
            this.TxtSegundoApellido.TextMarginLeft = 3;
            this.TxtSegundoApellido.TextMarginTop = 1;
            this.TxtSegundoApellido.TextPlaceholder = "Segundo Apellido";
            this.TxtSegundoApellido.UseSystemPasswordChar = false;
            this.TxtSegundoApellido.WordWrap = true;
            // 
            // LblNombresCliente
            // 
            this.LblNombresCliente.Dock = System.Windows.Forms.DockStyle.Top;
            this.LblNombresCliente.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LblNombresCliente.Location = new System.Drawing.Point(0, 0);
            this.LblNombresCliente.Name = "LblNombresCliente";
            this.LblNombresCliente.Size = new System.Drawing.Size(783, 43);
            this.LblNombresCliente.TabIndex = 0;
            this.LblNombresCliente.Text = "¿Cómo se llama el cliente?";
            this.LblNombresCliente.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // FrmEditorCliente
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.PnlPrincipal);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "FrmEditorCliente";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Editor Cliente";
            this.PnlPrincipal.ResumeLayout(false);
            this.FlwPnlBotones.ResumeLayout(false);
            this.TbPnlUbicacion.ResumeLayout(false);
            this.TbPnlOtrosDatos.ResumeLayout(false);
            this.TbPnlNombresCliente.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel PnlPrincipal;
        private System.Windows.Forms.Label LblNombresCliente;
        private System.Windows.Forms.TableLayoutPanel TbPnlNombresCliente;
        private Bunifu.UI.WinForms.BunifuTextBox TxtPrimerNombre;
        private Bunifu.UI.WinForms.BunifuTextBox TxtSegundoNombre;
        private Bunifu.UI.WinForms.BunifuTextBox TxtPrimerApellido;
        private Bunifu.UI.WinForms.BunifuTextBox TxtSegundoApellido;
        private System.Windows.Forms.Label LblOtrosDatos;
        private System.Windows.Forms.TableLayoutPanel TbPnlOtrosDatos;
        private Bunifu.UI.WinForms.BunifuTextBox TxtTelefono;
        private Bunifu.UI.WinForms.BunifuTextBox TxtDireccion;
        private System.Windows.Forms.Label LblUbicacion;
        private System.Windows.Forms.TableLayoutPanel TbPnlUbicacion;
        private System.Windows.Forms.Label LblDepartamento;
        private System.Windows.Forms.Label LblMunicipio;
        private System.Windows.Forms.ComboBox CmbDepartamentos;
        private System.Windows.Forms.ComboBox CmbMunicipios;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.FlowLayoutPanel FlwPnlBotones;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnGuardar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnLimpiar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCancelar;
    }
}